<script setup lang="ts">
import{onMounted,ref}from"vue";import{ElMessage}from"element-plus";import type{CreationDraft}from"../../../shared/contracts";import type{TextStyle}from"../../../shared/media-style";import SubtitleStyleEditor from"./SubtitleStyleEditor.vue";import TitleStyleEditor from"./TitleStyleEditor.vue";import PhoneCanvasPreview from"./PhoneCanvasPreview.vue";
type Bgm=NonNullable<CreationDraft["bgm"]>;const props=defineProps<{bgm:Bgm|null;voiceVolume:number;subtitleStyle:TextStyle;titleStyle:TextStyle;title:string;sampleText:string}>();const emit=defineEmits<{"update:bgm":[Bgm|null];"update:voiceVolume":[number];"update:subtitleStyle":[TextStyle];"update:titleStyle":[TextStyle]}>();
const tracks=ref<Array<{path:string;name:string;format:string}>>([]),invalidCount=ref(0),presets=ref<Awaited<ReturnType<typeof window.autocut.getStylePresets>>>([]),selectedPreset=ref("__random__"),presetName=ref(""),showPreviewBackground=ref(true);
async function chooseFile(){const path=await window.autocut.selectBgmFile();if(path)emit("update:bgm",{sourceType:"file",path,mode:"fixed",volume:.16,fadeInSec:1,fadeOutSec:1})}
async function chooseFolder(){const path=await window.autocut.selectBgmFolder();if(!path)return;const result=await window.autocut.scanAudioLibrary({folderPath:path,recursive:true});tracks.value=result.tracks;invalidCount.value=result.invalid.length;emit("update:bgm",{sourceType:"folder",path,mode:"random",volume:.16,fadeInSec:1,fadeOutSec:1})}
async function applyPreset(id:string){await window.autocut.saveStylePresetSelection?.(id);if(id==="__random__")return;const p=presets.value.find(v=>v.id===id);if(p){emit("update:subtitleStyle",structuredClone(p.subtitleStyle));emit("update:titleStyle",structuredClone(p.titleStyle))}}
async function savePreset(){const name=presetName.value.trim();if(!name)return ElMessage.warning("请输入样式模板名称");const preset={id:globalThis.crypto?.randomUUID?.()??`style-${Date.now()}`,name,subtitleStyle:structuredClone(props.subtitleStyle),titleStyle:structuredClone(props.titleStyle)};presets.value=await window.autocut.saveStylePresets([...presets.value,preset]);selectedPreset.value=preset.id;await window.autocut.saveStylePresetSelection?.(preset.id);presetName.value="";ElMessage.success("字幕与标题组合模板已保存")}
async function deletePreset(){if(selectedPreset.value==="__random__")return;presets.value=await window.autocut.saveStylePresets(presets.value.filter(p=>p.id!==selectedPreset.value));selectedPreset.value="__random__";await window.autocut.saveStylePresetSelection?.("__random__");ElMessage.success("样式模板已删除")}
onMounted(async()=>{const getSelection=window.autocut.getStylePresetSelection?.bind(window.autocut);[presets.value,selectedPreset.value]=await Promise.all([window.autocut.getStylePresets(),getSelection?getSelection():Promise.resolve("__random__")]);if(selectedPreset.value!=="__random__"&&!presets.value.some(item=>item.id===selectedPreset.value)){selectedPreset.value="__random__";await window.autocut.saveStylePresetSelection?.("__random__")}});
</script>
<template><aside class="media-panel"><header><h3>背景音乐、字幕与标题</h3><p>左侧精细设置，右侧固定 9:16 实时预览。</p></header><div class="design-grid"><div class="controls">
 <section><strong>声音混合</strong><div class="actions"><el-button @click="chooseFile">选择单曲</el-button><el-button @click="chooseFolder">选择文件夹</el-button></div><p class="path">{{bgm?.path||'未选择，支持 MP3 / WAV / M4A / AAC / FLAC'}}</p><el-select v-if="bgm?.sourceType==='folder'" :model-value="bgm.mode" @update:model-value="$emit('update:bgm',{...bgm,mode:$event})"><el-option label="随机" value="random"/><el-option label="顺序" value="sequential"/></el-select><p v-if="tracks.length">{{tracks.length}} 首可用，{{invalidCount}} 首无法读取</p><div class="mix"><label>人声音量 {{voiceVolume.toFixed(1)}}<el-slider :model-value="voiceVolume" :min="0" :max="3" :step=".1" @update:model-value="$emit('update:voiceVolume',Number($event))"/></label><label v-if="bgm">背景音乐音量 {{bgm.volume.toFixed(2)}}<el-slider :model-value="bgm.volume" :min="0" :max="1" :step=".01" @update:model-value="$emit('update:bgm',{...bgm,volume:Number($event)})"/></label></div></section>
 <section class="template"><strong>字幕与标题样式模板</strong><el-select v-model="selectedPreset" @change="applyPreset"><el-option label="随机样式模板（批量任务自动轮换）" value="__random__"/><el-option v-for="p in presets" :key="p.id" :label="p.name" :value="p.id"/></el-select><div class="actions"><el-input v-model="presetName" placeholder="输入模板名称"/><el-button type="primary" @click="savePreset">保存当前样式</el-button><el-button :disabled="selectedPreset==='__random__'" @click="deletePreset">删除</el-button></div></section>
 <SubtitleStyleEditor :model-value="subtitleStyle" @update:model-value="$emit('update:subtitleStyle',$event)"/><TitleStyleEditor :model-value="titleStyle" @update:model-value="$emit('update:titleStyle',$event)"/>
 </div><div class="preview"><div><strong>成片实时预览</strong><span>9:16 · 1080×1920</span></div><el-switch v-model="showPreviewBackground" active-text="场景背景" inactive-text="深色背景"/><PhoneCanvasPreview :subtitle-style="subtitleStyle" :title-style="titleStyle" :title="title" :subtitle="sampleText" :show-background="showPreviewBackground"/></div></div></aside></template>
<style scoped>.media-panel{display:grid;gap:18px}.media-panel h3,.media-panel p{margin:0}.media-panel header p,.path{color:var(--text-muted);font-size:12px;word-break:break-all}.design-grid{display:grid;grid-template-columns:minmax(0,1fr) 390px;gap:24px;align-items:start}.controls{display:grid;gap:24px}.controls>section{display:grid;gap:12px;padding-bottom:22px;border-bottom:1px solid var(--border)}.actions{display:flex;gap:9px;flex-wrap:wrap}.actions .el-input{flex:1;min-width:220px}.mix{display:grid;grid-template-columns:1fr 1fr;gap:20px}.mix label{display:grid;gap:8px}.preview{position:sticky;top:90px;display:grid;gap:16px;padding:18px;border-radius:18px;background:#f4f4f0}.preview>div{display:flex;justify-content:space-between}.preview span{color:var(--text-muted);font-size:12px}.preview :deep(.phone-canvas){margin:auto}@media(max-width:1100px){.design-grid{grid-template-columns:1fr}.preview{position:static}.mix{grid-template-columns:1fr}}</style>
